### ISSUE TITLE
Add issue template for new projects

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/community#101]
### Description
We should provide an issue template for proposing new projects (and perhaps also other project lifecycle changes). The current template from https://github.com/eiffel-community/.github/tree/master/.github doesn't apply in those cases.

### Motivation
The current sole issue template isn't a good fit for a relatively common use case and one that people seldom embark on, i.e. there's a good chance that every time a user proposes a new project confusion will arise.

### Exemplification
N/A

### Benefits
Providing a good template based on [PROJECT_LIFECYCLE.md](https://github.com/eiffel-community/community/blob/master/PROJECT_LIFECYCLE.md) is obviously beneficial for users and maintainers alike.

### Possible Drawbacks
We might also have to migrate aforementioned legacy template (https://github.com/eiffel-community/.github/blob/master/.github/ISSUE_TEMPLATE.md) to the new-style format that supports multiple templates. Well, that's perhaps not really a drawback but something that should be done anyway.

**Comment by magnusbaeck** [comment]
Disappointed. Quoting https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file,

> For example, anyone who creates an issue or pull request in a repository that does not have its own CONTRIBUTING file will see a link to the default CONTRIBUTING file. If a repository has any files in its own .github/ISSUE_TEMPLATE folder, including issue templates or a config.yml file, none of the contents of the default .github/ISSUE_TEMPLATE folder will be used.

it's clear that if we want to add another issue template we also have to include the existing templates from the github.com/eiffel-community/.github repository. That's annoying but perhaps no a dealbreaker as these templates are very rarely updated.

**Comment by m-linner-ericsson** [comment]
The community repository is a bit special so maybe we can live with the fact that it will not use the `.github` files. I think it would be more beneficial to have multiple issue templates in this repository than limiting us by trying to reduce duplication.

**Comment by magnusbaeck** [comment]
Yes, agreed. When https://github.com/eiffel-community/.github/issues/8 is merged both repositories will have the same template directory structure so it'll be trivial to keep them in sync. I'll send a PR.
