### ISSUE TITLE
New project "go-eiffel"

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/community#102]
### Name 
Go package for Eiffel events (aka go-eiffel)

### Description
When working with Eiffel events it's beneficial to have them available as formal types in the language you're using. This is especially true for typed languages like Java and Go where working with untyped maps quickly becomes inconvenient. This project will provide a Go package with types (mostly structs) that mirror the JSON schemas in the Eiffel specification and code to simplify serialization and deserialization of such values to and from JSON.

The Go code may be generated in whole or in part from the JSON schemas, either with existing third-party tools or with a bespoke tool included in the package.

### Project license
Apache Open Source License 2.0

### Name of initial maintainers
Magnus Bäck (@magnusbaeck)
Tobias Persson (@t-persson)
Felix Hall (TBD)
Jonas Alfredsson (@JonasAlfredsson)

### Infrastructure needs
Git repository: go-eiffel

One could argue that this name isn't descriptive enough, but keep in mind that the SCM repository URL is used as the import name in Go, so choosing a very long and descriptive name will come at a cost in the source code (or require that users always alias the imported package).

**Comment by e-backmark-ericsson** [comment]
Is this intended as a generic interface for any Eiffel related tool, such as ER, REMReM, EI and others, or just for one of them? Maybe eiffel-go-client/-library is a better name if the intention is to have a generic library written in Go that can interface any Eiffel component? Of eiffel-remrem-client if the intention is to interface REMReM only.

**Comment by magnusbaeck** [comment]
It's a client library suitable for anything written in Go that wants to interact with Eiffel events and their JSON representations. It's the Go equivalent of https://github.com/eiffel-community/eiffel-remrem-semantics/tree/master/src/main/java/com/ericsson/eiffel/semantics/events.

Interaction with REMReM or any other API won't be part of the library. If we want to be a bit more specific than go-eiffel then go-eiffelevents would be a good fit. Better, actually, now that I think about it.

**Comment by m-linner-ericsson** [comment]
I might be off here but isn't this what other people call a SDK eg. https://github.com/cloudevents/spec#sdks and https://github.com/cdfoundation/sig-events/tree/main/cde/sdk/go

**Comment by magnusbaeck** [comment]
Yes, it could be called an SDK. In that case go-eiffelevents-sdk could be a suitable name. Possibly just go-sdk, although there could be other kinds of Eiffel-related Go SDKs (like, say, a wrapper for submitting events to REMReM).

**Comment by e-backmark-ericsson** [comment]
> It's the Go equivalent of https://github.com/eiffel-community/eiffel-remrem-semantics/tree/master/src/main/java/com/ericsson/eiffel/semantics/events.

That's reasonable. We should probably break out that part of REMReM Semantics to an "eiffelevents-java-sdk" or similar.
It has no knowledge of any other Eiffel eco-system services/tools then I suppose, but is just a pure Eiffel Event library for the given programming language?

I propose "eiffelevents-go-sdk" for this project, but "go-eiffelevents-sdk" would be ok as well.

**Comment by m-linner-ericsson** [comment]
Looking at https://github.com/cloudevents/spec#sdks they list the name of the programming language last. For us that would look like this:

* eiffelevents-sdk-go
* eiffelevents-sdk-java
* eiffelevents-sdk-python

If we want to have the "eiffelevents" part at all.

**Comment by magnusbaeck** [comment]
I like eiffelevents-sdk-$LANG. The advantage of potentially having multiple SDKs per language (i.e. $SDKTYPE-sdk-$LANG rather than just sdk-$LANG) would be that different SDKs very well could have different owners. For example, a REMReM client SDK would probably be owned by the REMReM maintainers while an event SDK (i.e. what's being proposed in this issue) probably is maintained by someone else.

This is arguably very similar to the language dimension of the repo name; it makes sense to have $LANG somewhere in the repo name since SDKs for different languages are likely to have different maintainers.

**Comment by e-backmark-ericsson** [comment]
I also like eiffelevents-sdk-$LANG, so I hereby accept eiffelevents-sdk-go as a new Eiffel Community project :)

**Comment by magnusbaeck** [comment]
@m-linner-ericsson, I'm going to assume you're on board with eiffelevents-sdk-go since you made the proposal.

I should be able to start working on this next week.

**Comment by m-linner-ericsson** [comment]
👍
