### ISSUE TITLE
Why are the tables in CONTACT.md and PROJECTS.md nearly identical?

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/community#106]
### Description
As @magnusbaeck noticed in https://github.com/eiffel-community/community/pull/104 we have nearly identical tables listing projects in both Contact and Projects. Why do we need two tables? Can they be merged to one?

### Motivation
The current setup can be confusing and we could have problems with updates in one table but not the other

### Exemplification

From https://github.com/eiffel-community/community/blob/master/PROJECTS.md

| Project Name | Project Description | Project Maintainers | Project Lifecycle Stage |
| ------------ | ------------------- | ------------------- | ----------------------- |
| [Eiffel Protocol](https://github.com/eiffel-community/eiffel) | Eiffel is a protocol for technology agnostic machine-to-machine communication in continuous integration and delivery pipelines, aimed at securing scalability, flexibility and traceability. | [eiffel-protocol-maintainers](https://github.com/orgs/eiffel-community/teams/eiffel-protocol-maintainers/members) | [Graduated](./PROJECT_LIFECYCLE.md#stage-graduated) |
| [Eiffel Community](https://github.com/eiffel-community/community) | A project containing common Eiffel resources and information that does not belong to specific Eiffel repositories. | [eiffel-community-maintainers](https://github.com/orgs/eiffel-community/teams/eiffel-community-maintainers/members) | *Not Applicable* |

From https://github.com/eiffel-community/community/blob/master/CONTACT.md

Repository | Maintainer Team | Report Breach
--- | --- | ---
[eiffel (protocol)](https://github.com/eiffel-community/eiffel) | [eiffel-protocol-maintainers](https://github.com/orgs/eiffel-community/teams/eiffel-protocol-maintainers) | [eiffel-protocol-maintainers@googlegroups.com](mailto:eiffel-protocol-maintainers@googlegroups.com)
[community](https://github.com/eiffel-community/community) | [eiffel-community-maintainers](https://github.com/orgs/eiffel-community/teams/eiffel-community-maintainers) | [eiffel-community-maintainers@googlegroups.com](mailto:eiffel-community-maintainers@googlegroups.com)

### Benefits
N/A

### Possible Drawbacks
N/A

**Comment by magnusbaeck** [comment]
The Report Breach column should probably be renamed to indicate that it's a general mailing list for the project's maintainers.
