### ISSUE TITLE
Community folder or project to archive presentations

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/community#108]
### Description
We should have a folder in the community repository, or a project of its own, to store all presentations created by the community, and presentations given by others to the community.

### Motivation
Easy to find existing presentations. Possible to reuse (parts of) old presentations.

### Exemplification
"What is Eiffel?", "Event graphs explained", all summit presentations etc

### Benefits
See motivation

### Possible Drawbacks
None

**Comment by magnusbaeck** [comment]
Or the github.io repo? This is something we'll want to surface on the web.

**Comment by e-backmark-ericsson** [comment]
I think the community repo would suit better since we might want to store presentations that are not directly connected to a summit or such. They can still be linked from the github.io page of course
