### ISSUE TITLE
New project "eiffelevents-sdk-dotnet"

### ISSUE THREAD

**Issue by erkist** [eiffel-community/community#121]
### Name
eiffelevents-sdk-dotnet

### Description
.NET library for creating, serializing/deserializing, publishing and subscribing to Eiffel events,

### Project license
Apache 2.0

### Names of initial maintainers
Ahmed Abou Elfotouh @AhmedAbouElfotouh
Fady Kamil @fadykamil
Erik Sternerson @erkist

### Infrastructure needs
Git repository eiffelevents-sdk-dotnet (with content from https://github.com/widerscale/eiffelevents-sdk-dotnet )

**Comment by magnusbaeck** [comment]
LGTM

**Comment by e-backmark-ericsson** [comment]
LGTM

**Comment by erkist** [comment]
Based on  my understanding of the process this proposal now has 3/5 community maintainer votes, meaning simple majority, meaning it is approved.

Do I create the repo or does someone else need to do that?

**Comment by magnusbaeck** [comment]
Yes, you're good to go.

You should be able to create the repository and the maintainer team yourself now that you're a member of the eiffel-community organization.

I have the Gimp file used to produce https://github.com/eiffel-community/eiffelevents-sdk-go/blob/master/images/logo.png laying around locally and it should be trivial to replace "Go" with ".NET" and export a PNG that you can use in your repo.
