### ISSUE TITLE
Clarify process for creation of new project

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/community#123]
### Description
The [current instruction](https://github.com/eiffel-community/community/blob/master/PROJECT_LIFECYCLE.md#project-acceptance-process) on how to create a new project in the Eiffel Community GitHub organization is not clear enough. It needs to state who should do what and include additional documents to update.

### Motivation
Clarity on responsibilities when new projects are created.

### Exemplification
Include update of CONTACTS.md in the instruction and provide info on the GitHub project creation process.

### Benefits
Clarity

### Possible Drawbacks
-

**Comment by m-linner-ericsson** [comment]
This could now be closed @e-backmark-ericsson or?

**Comment by e-backmark-ericsson** [comment]
Yes
