### ISSUE TITLE
Move and remove duplicate documents from other repositories

### ISSUE THREAD

**Issue by fdegir** [eiffel-community/community#13]
As an Eiffel Community Member, I would like the duplicated community documentation moved from other repositories to community repository so that I can have one set of guidelines for all Eiffel Projects and the community.

**Comment by henning-roos** [comment]
I closed this issue, prematurely, it was only partly finished. Working on better a complete solution now

**Comment by henning-roos** [comment]
By the way, @fdegir, what does the "community-bootstrap" label mean?

**Comment by henning-roos** [comment]
The following repos have their own version of CODE_OF_CONDUCT.md, CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md and/or ISSUE_TEMPLATE.md:
- https://github.com/eiffel-community/community
- https://github.com/eiffel-community/eiffel-remrem
- https://github.com/eiffel-community/eiffel-remrem-publish
- https://github.com/eiffel-community/eiffel-remrem-generate
- https://github.com/eiffel-community/eiffel-remrem-semantics
- https://github.com/eiffel-community/eiffel-remrem-parent
- https://github.com/eiffel-community/eiffel-remrem-protocol-interface
- https://github.com/eiffel-community/eiffel-remrem-shared
- https://github.com/eiffel-community/eiffel-intelligence
- https://github.com/eiffel-community/eiffel-intelligence-frontend
- https://github.com/eiffel-community/eiffel-easy2use
- https://github.com/eiffel-community/eiffel-graphql-api
- https://github.com/eiffel-community/eiffel-gerrit-plugin
- https://github.com/eiffel-community/eiffel-vici
- https://github.com/eiffel-community/eiffel-pythonlib
- https://github.com/eiffel-community/eiffel-gerrit-herald
- https://github.com/eiffel-community/eiffel-gerrit-lib
- https://github.com/eiffel-community/eiffel-sepia
- https://github.com/eiffel-community/eiffel
- https://github.com/eiffel-community/eiffel-event-repository
- https://github.com/eiffel-community/eiffel-jenkins-plugin

**Comment by henning-roos** [comment]
Issue is now solved. There are no longer any duplicate files of Code of Conduct and Contributing in the community --- they only exists in the https://github.com/eiffel-community/.github repo and github solves the rest automatically.

See comment history for details of what has been done and https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file for more information of default health files.
