### ISSUE TITLE
Document how issue requirement for PRs should be handled for new repositories

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/community#138]
### Description
We currently have a requirement to connect all PRs to an issue. This makes sense for non-trivial bugs and features but isn't very useful for new development in new repositories. We should attempt to figure out a looser policy that apply in such circumstances.

### Motivation
Writing bespoke issues for every PR during iterative development isn't useful to anyone, nor is having a generic feature development issue that's reused for multiple PRs.

### Exemplification
N/A

### Benefits
Less bureaucracy and waste.

### Possible Drawbacks
None.

**Comment by e-backmark-ericsson** [comment]
This issue relates to #177
