### ISSUE TITLE
Inconsistent name of maintainer team for eiffel-graphql-api

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/community#165]
### Description
The GitHub team used for the maintainers of eiffel-graphql-api is named "eiffel-graphql-api" rather than "eiffel-graphql-api-maintainer" which would've been the expected. We should rename the team and all references to it (PROJECTS.md in this repo as well as https://github.com/eiffel-community/eiffel-graphql-api/blob/master/CODEOWNERS).

### Motivation
Consistency and simplified automation.

### Exemplification
I'm tasked with listing all maintainers for the 2023 TC elections and want to filter the list of GitHub teams in the organization to only cover maintainer teams, but because of the naming used for this team I can't just apply a "-maintainers$" regexp.

### Benefits
See Motivation, above.

### Possible Drawbacks
None, as long as we don't miss updating any references.

**Comment by magnusbaeck** [comment]
Are you okay with this @fredjn and @t-persson?

**Comment by fredjn** [comment]
It’s fine by me.

fre 10 mars 2023 kl. 10:03 skrev Magnus Bäck ***@***.***>:

**Comment by t-persson** [comment]
Yes, its fine

**Comment by magnusbaeck** [comment]
Team has been renamed and all known references have been updated. Closing.
