### ISSUE TITLE
Add presentations from Eiffel summit 2023.1

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/community#171]
### Description
We should have the presentations from the Eiffel Summit 2023.1 uploaded to the `presentations/eiffel_summit_2023.1` folder in this repository.

### Motivation
To keep presentations for future use

### Exemplification
Add ppt:s, pdf:s or similar

### Benefits
-

### Possible Drawbacks
-

**Comment by magnusbaeck** [comment]
Preferably PDFs because it's a more standardized format and it renders on GitHub so you don't have to download the file.

**Comment by magnusbaeck** [comment]
Are we waiting for any more slides or should we close?

**Comment by e-backmark-ericsson** [comment]
We're waiting for slides from @erkist

**Comment by e-backmark-ericsson** [comment]
@erkist will you add yours as well?
