### ISSUE TITLE
Simplify issue creation policy with updated templates for PRs and issues

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/community#177]
### Description

The TC have deemed the current process for creating issues as a bit cumbersome. We should thus update the templates and process to simplify for the community to create issues and post PRs. The task would contain:

- [ ] Update the issue creation policy
- [ ] Create a new template for issues
- [ ] Create a new template for PRs

### Motivation

The current process sometimes hinders us more than helps us.

### Exemplification

- Maybe take some inspiration from https://github.com/k8up-io/k8up/issues/new/choose ?
- Or for issues use something like: Background, Change, Motivation/Benefit, Drawbacks

### Benefits

With a simpler process it make creating issues and PR easier

### Possible Drawbacks
 
None that I can think of

**Comment by e-backmark-ericsson** [comment]
When taking on this issue we should also reflect on if we'd like to use some more advanced template features, like drop-down lists and such, when creating issues/PRs. Examples of such can be seen here: https://github.com/k8up-io/k8up/security/advisories/new

**Comment by e-backmark-ericsson** [comment]
The "issue creation policy", is that this one: https://github.com/eiffel-community/.github/blob/master/CONTRIBUTING.md, or is that defined somewhere else?

**Comment by e-backmark-ericsson** [comment]
> The "issue creation policy", is that this one: https://github.com/eiffel-community/.github/blob/master/CONTRIBUTING.md, or is that defined somewhere else?

@m-linner-ericsson , does this change then cover for the needed update of the 'issue creation policy': https://github.com/eiffel-community/.github/pull/21/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R39 ?

**Comment by m-linner-ericsson** [comment]
> > The "issue creation policy", is that this one: https://github.com/eiffel-community/.github/blob/master/CONTRIBUTING.md, or is that defined somewhere else?
> 
> @m-linner-ericsson , does this change then cover for the needed update of the 'issue creation policy': https://github.com/eiffel-community/.github/pull/21/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R39 ?

Yes that would cover the "Issue creation policy" in my head at least.
