### ISSUE TITLE
Add community recommendation for code style and test coverage application

### ISSUE THREAD

**Issue by a-breid-ericsson** [eiffel-community/community#20]
Code style and test coverage applications is used to ensure that all commits follow a decided code standard and that code is of good enough quality. Github has several such applications in their Marketplace, some is free to use on open source projects while others have a monthly fee.

The Eiffel community should approve and give recommendations for which of those applications that could be used in the repositories. To help the community to take such a decision we have compared several free alternatives and can after that propose a suggestion for the decision to take. Once the decision has been taken those applications should be opened to be used as a 3rd party application to all repositories in the Eiffel community.

**The candidates is currently:**

- Coveralls
- Codebeat
- Code Factor
- Codacy

The recommendation is to approve the use of **Coveralls** and **Codacy** since they may be used to complement each other, where Coveralls is to be used to ensure test coverage and Codacy is to be used for code quality check. None of the applications seems to work well with both test coverage and code quality checks, although Codacy as the only application that should be able to handle both.

Attached to this issue is a document with more detail description, pros and cons with the applications.
[github code style comparisons.xlsx](https://github.com/eiffel-community/community/files/3477441/github.code.style.comparisons.xlsx)

**Comment by e-pettersson-ericsson** [comment]
In Eiffel Intelligence we have decided to use Codacy for both code style check and show test coverage status. [See implementation details here](https://github.com/eiffel-community/eiffel-intelligence/pull/320)

**Comment by e-pettersson-ericsson** [comment]
I haven't seen any arguments to use any other tool for code style check/test coverage so is it safe to assume that Codacy can (and will) be used for repositories in the Eiffel community?

**Comment by henning-roos** [comment]
Yes I think we can assume that. I also agree with this decision.
See also https://github.com/eiffel-community/community/pull/21

I consider this issue closed now. Please open a new ticket referring to this issue if you do not agree with this.
