### ISSUE TITLE
Add markup to landscape picture showing non-graduatable projects

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/community#200]
### Description

The "community & support" repos in https://eiffel-community.github.io/community.html should be marked in a way to make it clear that they are not meant to be graduated.  They are implicitly graduated as being maintained by TC (?)

### Motivation

Clear distinction between project that can graduate and those that can not.

### Benefits

Now people might think those projects have a Sandbox status even though they don't.

### Possible Drawbacks
 
For the reader of the landscape picture it might confuse more with additional states.

**Comment by m-linner-ericsson** [comment]
Starting to wonder if the idea creates more confusion by an additional state. Posting an example
![landscape-non-graduatable](https://github.com/eiffel-community/community/assets/54929896/d735b25a-e47c-41f6-8378-a57d85ea51f8)

compare that with a version where all projects instead have graduated

![landscape-graduated-exampel](https://github.com/eiffel-community/community/assets/54929896/2c7ff891-2259-4afa-89a7-39cceb643fa4)

What causes the least confusion?

**Comment by magnusbaeck** [comment]
I think it's a bit cluttered. If all the Community & Support repos are non-graduatable, perhaps just add a sentence to that effect along the bottom of the box?
