### ISSUE TITLE
Setup slack channel for Eiffel Community

### ISSUE THREAD

**Issue by henning-roos** [eiffel-community/community#30]
### Description
Setup a slack channel for Eiffel community

### Motivation
We see the need of an instant messaging app. Slack was proposed at Eiffel Summit 2019.2 as the best alternative.

**Comment by henning-roos** [comment]
Make sure to add a link to the channel somewhere easy to find

**Comment by ewelinawilkosz** [comment]
eiffel-workspace.slack.com up and running, will announce via google group
