### ISSUE TITLE
Add Slack to contact information

### ISSUE THREAD

**Issue by e-pettersson-ericsson** [eiffel-community/community#33]
### Description
Add information about our [Eiffel Slack](eiffel-workspace.slack.com) so people new to the community can ask questions or join the community easier.

### Motivation
People new to the community needs to know how to get in touch with community members. Outside of GitHub we have Google groups and Slack but only Google groups is mentioned currently.

### Exemplification
Something like

```
# Contact
* Mail list
* Slack channel
* etc ...
```
can be placed in the README.md or in the CONTACT.md perhaps?

### Benefits
Easier access to someone in the Eiffel community, aside from a mail list.

**Comment by e-pettersson-ericsson** [comment]
Courtesy of @ewelinawilkosz [this link](https://join.slack.com/t/eiffel-workspace/shared_invite/enQtOTI3MzEzMzY4Mzg0LTA3NDVmNjgzZjk1YTFjNzk5OWE4MjExYzE1ODU1NzA1YzY5MzhlZmYxZmIwMzhiM2ExOWM4ZGJlYzdkN2M5OTE) should be a permanent invite link.

**Comment by SantoshNC68** [comment]
Should this be then replaced or put together with the google groups?

**Comment by e-pettersson-ericsson** [comment]
@SantoshNC68 I was thinking we could just add it and keep both as contact information.
