### ISSUE TITLE
Create Technical Committee Charter

### ISSUE THREAD

**Issue by fdegir** [eiffel-community/community#4]
As an Eiffel Community Member, I would like the Technical Committee Charter documented so that I know the roles, responsibilities, and way of working of the committee.

**Comment by m-linner-ericsson** [comment]
@fdegir Do you feel https://github.com/eiffel-community/community/blob/master/GOVERNANCE.md covers this or are there things missing?

**Comment by e-backmark-ericsson** [comment]
The GOVERNANCE document includes the requested information and therefore this issue is now closed.
