### ISSUE TITLE
Add summit presentations folder

### ISSUE THREAD

**Issue by e-backmark-ericsson** [eiffel-community/community#45]
### Description
We should have a folder where we can put presentations and more from our summits

### Motivation
Version controlled summit material

### Possible Drawbacks
Clutter the repo?

**Comment by fredjn** [comment]
So I guess we can close this issue, or is there something that #46 didn't address?

**Comment by k-hallen-ericsson** [comment]
@e-backmark-ericsson close this?

**Comment by e-backmark-ericsson** [comment]
Done, so let's close it
