### ISSUE TITLE
Identify List of Eiffel Projects

### ISSUE THREAD

**Issue by fdegir** [eiffel-community/community#6]
As an Eiffel Community Member, I would like the list of existing Eiffel projects and their repositories documented so that I know what is developed by Eiffel Community and where.

**Comment by henning-roos** [comment]
@fdegir , you can find a list of projects and repositories by going to the root of [eiffel-community](https://github.com/eiffel-community), or was there something else you had in mind?

**Comment by fdegir** [comment]
@henning-roos this is about identifying what projects Eiffel community develops, mapping repositories to the projects, and finally creating maintainers groups for the projects so it becomes clear who looks after a certain projects and the repositories that form the project.

Some Linux Foundation communities have an existing method to work with this and here is an example.

https://github.com/opnfv/releng/blob/master/INFO.yaml

This file is for the project named Release Engineering in OPNFV Community. It lists project lead, committers (maintainers), meeting details as well as the repositories under that project. For Eiffel, it doesn't have to be like this exactly but a similar approach can be taken so when someone looks at an Eiffel repository, the person can get an idea about what group of maintainers work with the project, what repos are under the project and so on.

**Comment by e-backmark-ericsson** [comment]
@fdegir , is that INFO file parsed by some tool and automatically aggregated to some page somewhere for all repos in the organization? If not, why is it in yaml?

**Comment by fdegir** [comment]
@e-backmark-ericsson I'm not aware of the use of the file for aggregating information about all the projects someplace else but the file is used for granting people committer rights or removing rights on community Gerrit in addition to documenting project facts.

**Comment by e-backmark-ericsson** [comment]
Ah, so the format of the file is specific to some Gerrit granting plugin then? I'm just curious on what file format/syntax we should use. As all the Eiffel Community repos are in GitHub we should not set up a file that is Gerrit specific in the repos. If it instead would be possible to control the connection between GitHub Teams and such a file within the repo it would be interesting. Does anyone know if such exists? It would mean that to change what team has what authorities in a repo is done by updating a file in the repo itself.

**Comment by fdegir** [comment]
The format of the file was made up by us and not specific to Gerrit because we needed to make the info visible and use it even further for automation rather than sending mails here and there. 

For Eiffel, anything that doesn't add extra complexity would be useful and if there is an existing Github feature, that makes things even better. I quickly Googled about this and ended up reading people's thoughts about Github projects which I just clicked the Create Project button to see how it looks.

https://github.com/orgs/eiffel-community/projects

I see that you can create projects for the organization and then link repositories under them. The projects could also have own issue tracking boards and teams and so on. I'm not suggesting this is the way but it could be looked into and perhaps even tried with some dummy repos and a corresponding project.

**Comment by fdegir** [comment]
just to update: this issue is related to this PR: https://github.com/eiffel-community/community/pull/48

**Comment by fdegir** [comment]
Fixed by https://github.com/eiffel-community/community/pull/51
