### ISSUE TITLE
Create a private maillist for security/vulnerability reporting

### ISSUE THREAD

**Issue by fdegir** [eiffel-community/community#60]
### Description

Eiffel Community is in the process of documenting Security/Vulnerability Reporting and Response Process. As part of this process, a mail address to report security/vulnerability issues is required so the users can do that in a secure manner.

### Motivation

It is important to receive and handle security/vulnerability issues properly so the reports are available only to Eiffel Community Members who are responsible for handling such issues.

### Exemplification

N/A

### Benefits

Security/vulnerability issues are reported to and known by the Eiffel Community Members and not by public until they are fixed and disclosed.

### Possible Drawbacks

N/A

**Comment by fdegir** [comment]
@k-hallen-ericsson assigning this to you since you got an AP from the last TC meeting.

**Comment by k-hallen-ericsson** [comment]
eiffel-community-security@googlegroups.com is created.

**Comment by fdegir** [comment]
Thanks Kristofer. Closing the issue and we will close the AP during the meeting.
