### ISSUE TITLE
Document security/vulnerability reporting and response process

### ISSUE THREAD

**Issue by fdegir** [eiffel-community/community#61]
### Description

Eiffel Community needs to document the process it follows for security/vulnerability reporting and response so the users who identify such issues know where and how to report them. The process will also need to document who shall receive such reports, how they should be handled, fixed, and disclosed publicly.

### Motivation

Security/vulnerability issues shall be reported, addressed, and disclosed in a proper manner without exposing users with vulnerable software to risk.

### Exemplification

See processes of [Jenkins](https://www.jenkins.io/security/reporting/) and [Spinnaker](https://spinnaker.io/community/security/) as processes.

### Benefits

Security/vulnerability issues can be reported, addressed, and disclosed in a proper manner without exposing users with vulnerable software to risk.

### Possible Drawbacks

N/A

**Comment by k-hallen-ericsson** [comment]
I like the easy to understand setup that Spinnaker has. The hard part I assume is how we will handle a reported issue, especially when it is a community. Do we accept issues on all projects in the community? What kind of responsibility does the TC take? @fdegir do you know of any examples of the background process?

**Comment by fdegir** [comment]
I think we need to handle Eiffel as a whole so if someone finds a security/vulnerability issue in any projects/repos within eiffel-community organization, they should turn to one place to report this. This place could be a private maillist where very few people (e.g. security officers) can receive such reports so the reporters can disclose the issue without impacting other users who may be using vulnerable version.  This group of people can do the initial assessment in order to identify impacted  project(s) and pass that report to maintainers of the impacted project(s). TC responsibility here is to 

- document the process clearly
- get such private maillist created (something like eiffel-community-security@googlegroups.com)
- appoint security officers (2 to 4 people perhaps?)
- ensure security/vulnerability issues including issuing fixes followed by public disclosure are handled according to the documented process

I like the Spinnaker process as well.

**Comment by k-hallen-ericsson** [comment]
@fredjn should we create a page that describes the process? I think we can start with the spinnaker setup but we also need to describe the internal process when an inssue is reported.

**Comment by fredjn** [comment]
> @fredjn should we create a page that describes the process? I think we can start with the spinnaker setup but we also need to describe the internal process when an inssue is reported.

I agree, I can start a PR tomorrow drafting out something lightweight like spinnaker.

**Comment by fredjn** [comment]
@k-hallen-ericsson I sent you a hackMD link of my frist draft. Hopefully we can hash out a PR-worthy version from there.
