### ISSUE TITLE
New project: eiffel-playground

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/community#62]
### Description
Create a new project

Name: eiffel-playground
Description: A playground repository to test GitHub specific features not suitable to test with real repositories e.g. perform releases to trigger an automatic build engine, doing dummy pull requests to trigger automatic pipelines, etc.
License: Apache 2.0
Maintainers: All

**Comment by fdegir** [comment]
@eiffel-community/eiffel-community-maintainers 

We are starting to work on trialing the use of Nordix Infrastructure for Eiffel builds and we will need a new repository to do such trials without impacting existing/real projects and their repositories so could you please approve this request?

**Background**

This need, providing build capability for Eiffel Community, was first brought up by @magnusbaeck in https://github.com/eiffel-community/community/issues/47 and our plan is documented [here](https://hackmd.io/X3Nrxe4MRdSJI_lsTkSwiQ?view). The first step we intend to take on this direction is documented as [Phase 1](https://hackmd.io/X3Nrxe4MRdSJI_lsTkSwiQ?view#Phase-1-Evaluation-and-Setting-Up-the-Basics).

We had the very first meeting to get to know each other and have an early discussion on the proposed way forward today. You can see the minutes from [here](https://hackmd.io/X3Nrxe4MRdSJI_lsTkSwiQ?view#September-16-2020).

We will present this topic during the next Technical Committee Meeting and call broader community for participation in this topic on the maillist as well.

**Comment by k-hallen-ericsson** [comment]
Good plan, do I approve by saying it here?

**Comment by e-backmark-ericsson** [comment]
I approve this idea. Should a PR be opened to add the playground to the list of projects?

**Comment by fdegir** [comment]
> Good plan, do I approve by saying it here?

Yes or one of +1, 0, -1 works too.

> I approve this idea. Should a PR be opened to add the playground to the list of projects?

This will not be a "real" project so we may just skip adding it to project list.

**Comment by e-backmark-ericsson** [comment]
> This will not be a "real" project so we may just skip adding it to project list.
I believe it is better to be transparent than to assume that people understand that this is a not-to-be-considered-as-official repo by its name. I think it could be added to the projects list, but maybe just as a repo then, with project name something like 'not relevant'. Am I being too rigorous maybe? I can live with it not being mentioned there as well.

**Comment by fdegir** [comment]
You are right with what you think. Why I thought it may be ok for us to skip adding this to the project list is based on what I've seen done by some other communities which I put one of them below.

https://gerrit.opnfv.org/gerrit/admin/repos/q/filter:sandbox

In OPNFV, sandbox is not listed as project anywhere except in Release Engineering project's user guide, instructing the people to use the sandbox repos to test their gerrit access, play with gerrit, and so on.

But this doesn't mean we have to follow what they do and it is perfectly fine to add eiffel-playground to list of projects with the note you proposed.

**Comment by m-linner-ericsson** [comment]
So should I open a PR?

**Comment by fdegir** [comment]
I think we can open a PR and the project description could clearly state the project/repo is for GitHub trial purposes or something.

**Comment by henning-roos** [comment]
+1

**Comment by fdegir** [comment]
This request is approved during the TC meeting on September 28th.

https://hackmd.io/SCImga0nS1qSh3QvsEOAVQ?view#September-28-2020
