### ISSUE TITLE
Describe how to handle dependecies between repositories

### ISSUE THREAD

**Issue by m-linner-ericsson** [eiffel-community/community#73]
### Description
Describe how to handle dependencies between repositories.

Currently [Eiffel Intelligence Frontend](https://github.com/eiffel-community/eiffel-intelligence-frontend) is dependent on [Eiffel Intelligence ](https://github.com/eiffel-community/eiffel-intelligence). If the front-end requires a feature in the back-end there is no point in releasing or building Docker container for the front-end until the back-end has the functionality merged.

In ETOS on the other hand there is a wish to build the containers on every merge. 

### Motivation
Need a unified way of handling dependencies between repositories. 

### Exemplification
See description

### Benefits
Avoiding unusable releases and docker containers

### Possible Drawbacks
N/A

**Comment by fdegir** [comment]
@m-linner-ericsson I suppose this is duplicate of https://github.com/eiffel-community/community/issues/74?

**Comment by m-linner-ericsson** [comment]
Duplicate of https://github.com/eiffel-community/community/issues/74
