### ISSUE TITLE
Apply sandbox badge to the project repositories

### ISSUE THREAD

**Issue by fdegir** [eiffel-community/community#85]
### Description

Something to signal the level of maturity of tools is needed. As it is now we have a mix of (more or less) abandoned repositories, experimental code and production grade code.

This issue is about applying sandbox badge as described in [project lifecycle document](https://github.com/eiffel-community/community/blob/master/PROJECT_LIFECYCLE.md#project-lifecycle-stages).

### Motivation

Without this distinction it's more difficult than it should be for newcomers to get started. The overall impression of Eiffel suffers.

### Exemplification

When users deploying RemRem,, they ran into a number of unexpected problems. Refer to the issues filed in eiffel-remrem-generate and eiffel-remrem-publish.

### Benefits

Having information about the status of projects upfront makes it easier for potential users to estimate the effort needed for deployment.

### Possible Drawbacks

If we're not careful it might give the wrong impression and make users hesitant to try out, and contribute to, the development of new tools.

**Comment by e-backmark-ericsson** [comment]
All repos are now updated with the sandbox badge
