### ISSUE TITLE
Update governance document and remove bootstrap process

### ISSUE THREAD

**Issue by fdegir** [eiffel-community/community#90]
### Description

As documented in the [governance](https://github.com/eiffel-community/community/blob/master/GOVERNANCE.md#community-bootstrap-process), Eiffel Community has been operating in bootstrap mode and served by a special committee with appointed members named Bootstrap Technical Committee (BTC).
As part of the bootstrap phase, BTC created missing and updated existing community processes and procedures. 

BTC [agreed](https://hackmd.io/SCImga0nS1qSh3QvsEOAVQ?view#March-25-2021) to call for community elections to compose a new TC based on meritocracy which means that the governance document can be updated to reflect the fact that the community concluded the bootstrap phase and switched to normal mode of operations.
Because of this, it is required to update the governance document, remove the bootstrap process, and make necessary amendments.

Please note that this must be approved by the newly elected TC and driven by the newly elected TC Chair and **not** by the BTC since newly elected TC may determine to take parts of the bootstrap process and incorporate it to governance.

### Motivation

Reflect the maturity of the community and keep the governance up to date.

### Exemplification

This is a common practice within open source communities.

### Benefits

Maturity of the community is communicated clearly & transparently and governance is kept up to date.

### Possible Drawbacks

N/A

**Comment by fdegir** [comment]
It would be good to add a sentence to the governance, linking to the bootstrap process so people can go back in history.

**Comment by e-backmark-ericsson** [comment]
I think it would be wise to provide the list of people of the new TC in the same PR as is used to remove the BTC. Will you do those updates at the same time?

**Comment by fdegir** [comment]
> I think it would be wise to provide the list of people of the new TC in the same PR as is used to remove the BTC. Will you do those updates at the same time?

I just noticed this comment thanks to @magnusbaeck so PR #95 adds the list of elected TC members.
